version: '3.4'

services:
  composeplayground:
    image: ${DOCKER_REGISTRY-}composeplayground
    build:
      context: .
      dockerfile: ComposePlayground/Dockerfile
    depends_on:
        - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    - elastic_data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    ports:
        - "5601:5601"
    depends_on:
        - elasticsearch